# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  database: maxprog_dev
  pool: 5
  username: ernesto
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: ernesto
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: ernesto
  password:

cucumber:
  <<: *TEST
